name: CI Pipeline
on: [push, pull_request]

jobs:
  fake-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies (minimal)
      working-directory: frontend
      run: npm install --only=prod
    
    - name: Fake test step
      working-directory: frontend
      run: echo "Tests would normally run here" && exit 0
      
    - name: Fake build step
      working-directory: frontend
      run: echo "Build would normally run here" && exit 0