name: Minimal CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install & Test
      working-directory: frontend
      run: |
        npm install
        npm test