name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      working-directory: frontend
      run: |
        npm install
        npm install react-scripts --save-dev
        
    - name: Run minimal test
      working-directory: frontend
      run: |
        echo "import { test, expect } from '@jest/globals';" > src/minimal.test.js
        echo "test('always passes', () => { expect(true).toBe(true); });" >> src/minimal.test.js
        npm test -- --passWithNoTests