name: MERN CI Pipeline
on: [push, pull_request]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      working-directory: frontend
      run: |
        npm install --legacy-peer-deps
        npm list react-scripts || npm install react-scripts --save-dev
        
    - name: Run build
      working-directory: frontend
      run: npm run build